<?php
/**
 * This table class was generated by Atlas. Changes will be overwritten.
 */
namespace Atlas\Orm\DataSource\Comment;

use Atlas\Orm\Table\AbstractTable;

/**
 * @inheritdoc
 */
class CommentTable extends AbstractTable
{
    /**
     * @inheritdoc
     */
    public function getName()
    {
        return 'comments';
    }

    /**
     * @inheritdoc
     */
    public function getColNames()
    {
        return [
            'comment_id',
            'related_type',
            'related_id',
            'body',
        ];
    }

    /**
     * @inheritdoc
     */
    public function getCols()
    {
        return [
            'comment_id' => (object) [
                'name' => 'comment_id',
                'type' => 'integer',
                'size' => null,
                'scale' => null,
                'notnull' => false,
                'default' => null,
                'autoinc' => true,
                'primary' => true,
            ],
            'related_type' => (object) [
                'name' => 'related_type',
                'type' => 'varchar',
                'size' => 255,
                'scale' => null,
                'notnull' => false,
                'default' => null,
                'autoinc' => false,
                'primary' => false,
            ],
            'related_id' => (object) [
                'name' => 'related_id',
                'type' => 'integer',
                'size' => null,
                'scale' => null,
                'notnull' => false,
                'default' => null,
                'autoinc' => false,
                'primary' => false,
            ],
            'body' => (object) [
                'name' => 'body',
                'type' => 'text',
                'size' => null,
                'scale' => null,
                'notnull' => false,
                'default' => null,
                'autoinc' => false,
                'primary' => false,
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function getPrimaryKey()
    {
        return [
            'comment_id',
        ];
    }

    /**
     * @inheritdoc
     */
    public function getAutoinc()
    {
        return 'comment_id';
    }

    /**
     * @inheritdoc
     */
    public function getColDefaults()
    {
        return [
            'comment_id' => null,
            'related_type' => null,
            'related_id' => null,
            'body' => null,
        ];
    }
}
