<?php
/**
 * This table class was generated by Atlas. Changes will be overwritten.
 */
namespace Atlas\Orm\DataSource\Page;

use Atlas\Orm\Table\AbstractTable;

/**
 * @inheritdoc
 */
class PageTable extends AbstractTable
{
    /**
     * @inheritdoc
     */
    public function getName()
    {
        return 'pages';
    }

    /**
     * @inheritdoc
     */
    public function getColNames()
    {
        return [
            'page_id',
            'title',
            'body',
        ];
    }

    /**
     * @inheritdoc
     */
    public function getCols()
    {
        return [
            'page_id' => (object) [
                'name' => 'page_id',
                'type' => 'integer',
                'size' => null,
                'scale' => null,
                'notnull' => false,
                'default' => null,
                'autoinc' => true,
                'primary' => true,
            ],
            'title' => (object) [
                'name' => 'title',
                'type' => 'varchar',
                'size' => 255,
                'scale' => null,
                'notnull' => false,
                'default' => null,
                'autoinc' => false,
                'primary' => false,
            ],
            'body' => (object) [
                'name' => 'body',
                'type' => 'text',
                'size' => null,
                'scale' => null,
                'notnull' => false,
                'default' => null,
                'autoinc' => false,
                'primary' => false,
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function getPrimaryKey()
    {
        return [
            'page_id',
        ];
    }

    /**
     * @inheritdoc
     */
    public function getAutoinc()
    {
        return 'page_id';
    }

    /**
     * @inheritdoc
     */
    public function getColDefaults()
    {
        return [
            'page_id' => null,
            'title' => null,
            'body' => null,
        ];
    }
}
