<?php
/**
 * This table class was generated by Atlas. Changes will be overwritten.
 */
namespace Atlas\Orm\DataSource\Course;

use Atlas\Orm\Table\AbstractTable;

/**
 * @inheritdoc
 */
class CourseTable extends AbstractTable
{
    /**
     * @inheritdoc
     */
    public function getName()
    {
        return 'courses';
    }

    /**
     * @inheritdoc
     */
    public function getColNames()
    {
        return [
            'course_subject',
            'course_number',
            'title',
        ];
    }

    /**
     * @inheritdoc
     */
    public function getCols()
    {
        return [
            'course_subject' => (object) [
                'name' => 'course_subject',
                'type' => 'char',
                'size' => 4,
                'scale' => null,
                'notnull' => false,
                'default' => null,
                'autoinc' => false,
                'primary' => true,
            ],
            'course_number' => (object) [
                'name' => 'course_number',
                'type' => 'int',
                'size' => null,
                'scale' => null,
                'notnull' => false,
                'default' => null,
                'autoinc' => false,
                'primary' => true,
            ],
            'title' => (object) [
                'name' => 'title',
                'type' => 'varchar',
                'size' => 20,
                'scale' => null,
                'notnull' => false,
                'default' => null,
                'autoinc' => false,
                'primary' => false,
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function getPrimaryKey()
    {
        return [
            'course_subject',
            'course_number',
        ];
    }

    /**
     * @inheritdoc
     */
    public function getAutoinc()
    {
        return '';
    }

    /**
     * @inheritdoc
     */
    public function getColDefaults()
    {
        return [
            'course_subject' => null,
            'course_number' => null,
            'title' => null,
        ];
    }
}
