<?php
/**
 * This table class was generated by Atlas. Changes will be overwritten.
 */
namespace Atlas\Orm\DataSource\Post;

use Atlas\Orm\Table\AbstractTable;

/**
 * @inheritdoc
 */
class PostTable extends AbstractTable
{
    /**
     * @inheritdoc
     */
    public function getName()
    {
        return 'posts';
    }

    /**
     * @inheritdoc
     */
    public function getColNames()
    {
        return [
            'post_id',
            'subj',
            'body',
        ];
    }

    /**
     * @inheritdoc
     */
    public function getCols()
    {
        return [
            'post_id' => (object) [
                'name' => 'post_id',
                'type' => 'integer',
                'size' => null,
                'scale' => null,
                'notnull' => false,
                'default' => null,
                'autoinc' => true,
                'primary' => true,
            ],
            'subj' => (object) [
                'name' => 'subj',
                'type' => 'varchar',
                'size' => 255,
                'scale' => null,
                'notnull' => false,
                'default' => null,
                'autoinc' => false,
                'primary' => false,
            ],
            'body' => (object) [
                'name' => 'body',
                'type' => 'text',
                'size' => null,
                'scale' => null,
                'notnull' => false,
                'default' => null,
                'autoinc' => false,
                'primary' => false,
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function getPrimaryKey()
    {
        return [
            'post_id',
        ];
    }

    /**
     * @inheritdoc
     */
    public function getAutoinc()
    {
        return 'post_id';
    }

    /**
     * @inheritdoc
     */
    public function getColDefaults()
    {
        return [
            'post_id' => null,
            'subj' => null,
            'body' => null,
        ];
    }
}
