<?php
/**
 * This table class was generated by Atlas. Changes will be overwritten.
 */
namespace Atlas\Orm\DataSource\Enrollment;

use Atlas\Orm\Table\AbstractTable;

/**
 * @inheritdoc
 */
class EnrollmentTable extends AbstractTable
{
    /**
     * @inheritdoc
     */
    public function getName()
    {
        return 'enrollments';
    }

    /**
     * @inheritdoc
     */
    public function getColNames()
    {
        return [
            'student_fn',
            'student_ln',
            'course_subject',
            'course_number',
            'grade',
            'points',
        ];
    }

    /**
     * @inheritdoc
     */
    public function getCols()
    {
        return [
            'student_fn' => (object) [
                'name' => 'student_fn',
                'type' => 'varchar',
                'size' => 10,
                'scale' => null,
                'notnull' => false,
                'default' => null,
                'autoinc' => false,
                'primary' => true,
            ],
            'student_ln' => (object) [
                'name' => 'student_ln',
                'type' => 'varchar',
                'size' => 10,
                'scale' => null,
                'notnull' => false,
                'default' => null,
                'autoinc' => false,
                'primary' => true,
            ],
            'course_subject' => (object) [
                'name' => 'course_subject',
                'type' => 'char',
                'size' => 4,
                'scale' => null,
                'notnull' => false,
                'default' => null,
                'autoinc' => false,
                'primary' => true,
            ],
            'course_number' => (object) [
                'name' => 'course_number',
                'type' => 'int',
                'size' => null,
                'scale' => null,
                'notnull' => false,
                'default' => null,
                'autoinc' => false,
                'primary' => true,
            ],
            'grade' => (object) [
                'name' => 'grade',
                'type' => 'int',
                'size' => null,
                'scale' => null,
                'notnull' => false,
                'default' => null,
                'autoinc' => false,
                'primary' => false,
            ],
            'points' => (object) [
                'name' => 'points',
                'type' => 'int',
                'size' => null,
                'scale' => null,
                'notnull' => false,
                'default' => null,
                'autoinc' => false,
                'primary' => false,
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function getPrimaryKey()
    {
        return [
            'student_fn',
            'student_ln',
            'course_subject',
            'course_number',
        ];
    }

    /**
     * @inheritdoc
     */
    public function getAutoinc()
    {
        return '';
    }

    /**
     * @inheritdoc
     */
    public function getColDefaults()
    {
        return [
            'student_fn' => null,
            'student_ln' => null,
            'course_subject' => null,
            'course_number' => null,
            'grade' => null,
            'points' => null,
        ];
    }
}
