<?php
/**
 * This table class was generated by Atlas. Changes will be overwritten.
 */
namespace Atlas\Orm\DataSource\Video;

use Atlas\Orm\Table\AbstractTable;

/**
 * @inheritdoc
 */
class VideoTable extends AbstractTable
{
    /**
     * @inheritdoc
     */
    public function getName()
    {
        return 'videos';
    }

    /**
     * @inheritdoc
     */
    public function getColNames()
    {
        return [
            'video_id',
            'title',
            'url',
        ];
    }

    /**
     * @inheritdoc
     */
    public function getCols()
    {
        return [
            'video_id' => (object) [
                'name' => 'video_id',
                'type' => 'integer',
                'size' => null,
                'scale' => null,
                'notnull' => false,
                'default' => null,
                'autoinc' => true,
                'primary' => true,
            ],
            'title' => (object) [
                'name' => 'title',
                'type' => 'varchar',
                'size' => 255,
                'scale' => null,
                'notnull' => false,
                'default' => null,
                'autoinc' => false,
                'primary' => false,
            ],
            'url' => (object) [
                'name' => 'url',
                'type' => 'varchar',
                'size' => 255,
                'scale' => null,
                'notnull' => false,
                'default' => null,
                'autoinc' => false,
                'primary' => false,
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function getPrimaryKey()
    {
        return [
            'video_id',
        ];
    }

    /**
     * @inheritdoc
     */
    public function getAutoinc()
    {
        return 'video_id';
    }

    /**
     * @inheritdoc
     */
    public function getColDefaults()
    {
        return [
            'video_id' => null,
            'title' => null,
            'url' => null,
        ];
    }
}
