<?php
/**
 * This table class was generated by Atlas. Changes will be overwritten.
 */
namespace Atlas\Orm\DataSource\Student;

use Atlas\Orm\Table\AbstractTable;

/**
 * @inheritdoc
 */
class StudentTable extends AbstractTable
{
    /**
     * @inheritdoc
     */
    public function getName()
    {
        return 'students';
    }

    /**
     * @inheritdoc
     */
    public function getColNames()
    {
        return [
            'student_fn',
            'student_ln',
            'degree_type',
            'degree_subject',
        ];
    }

    /**
     * @inheritdoc
     */
    public function getCols()
    {
        return [
            'student_fn' => (object) [
                'name' => 'student_fn',
                'type' => 'varchar',
                'size' => 10,
                'scale' => null,
                'notnull' => false,
                'default' => null,
                'autoinc' => false,
                'primary' => true,
            ],
            'student_ln' => (object) [
                'name' => 'student_ln',
                'type' => 'varchar',
                'size' => 10,
                'scale' => null,
                'notnull' => false,
                'default' => null,
                'autoinc' => false,
                'primary' => true,
            ],
            'degree_type' => (object) [
                'name' => 'degree_type',
                'type' => 'char',
                'size' => 2,
                'scale' => null,
                'notnull' => false,
                'default' => null,
                'autoinc' => false,
                'primary' => false,
            ],
            'degree_subject' => (object) [
                'name' => 'degree_subject',
                'type' => 'char',
                'size' => 4,
                'scale' => null,
                'notnull' => false,
                'default' => null,
                'autoinc' => false,
                'primary' => false,
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function getPrimaryKey()
    {
        return [
            'student_fn',
            'student_ln',
        ];
    }

    /**
     * @inheritdoc
     */
    public function getAutoinc()
    {
        return '';
    }

    /**
     * @inheritdoc
     */
    public function getColDefaults()
    {
        return [
            'student_fn' => null,
            'student_ln' => null,
            'degree_type' => null,
            'degree_subject' => null,
        ];
    }
}
