<?php
/**
 * This table class was generated by Atlas. Changes will be overwritten.
 */
namespace Atlas\Orm\DataSource\Gpa;

use Atlas\Orm\Table\AbstractTable;

/**
 * @inheritdoc
 */
class GpaTable extends AbstractTable
{
    /**
     * @inheritdoc
     */
    public function getName()
    {
        return 'gpas';
    }

    /**
     * @inheritdoc
     */
    public function getColNames()
    {
        return [
            'student_fn',
            'student_ln',
            'gpa',
        ];
    }

    /**
     * @inheritdoc
     */
    public function getCols()
    {
        return [
            'student_fn' => (object) [
                'name' => 'student_fn',
                'type' => 'varchar',
                'size' => 10,
                'scale' => null,
                'notnull' => false,
                'default' => null,
                'autoinc' => false,
                'primary' => true,
            ],
            'student_ln' => (object) [
                'name' => 'student_ln',
                'type' => 'varchar',
                'size' => 10,
                'scale' => null,
                'notnull' => false,
                'default' => null,
                'autoinc' => false,
                'primary' => true,
            ],
            'gpa' => (object) [
                'name' => 'gpa',
                'type' => 'decimal',
                'size' => 4,
                'scale' => 3,
                'notnull' => false,
                'default' => null,
                'autoinc' => false,
                'primary' => false,
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function getPrimaryKey()
    {
        return [
            'student_fn',
            'student_ln',
        ];
    }

    /**
     * @inheritdoc
     */
    public function getAutoinc()
    {
        return '';
    }

    /**
     * @inheritdoc
     */
    public function getColDefaults()
    {
        return [
            'student_fn' => null,
            'student_ln' => null,
            'gpa' => null,
        ];
    }
}
