<?php
/**
 * This table class was generated by Atlas. Changes will be overwritten.
 */
namespace Atlas\Orm\DataSource\Summary;

use Atlas\Orm\Table\AbstractTable;

/**
 * @inheritdoc
 */
class SummaryTable extends AbstractTable
{
    /**
     * @inheritdoc
     */
    public function getName()
    {
        return 'summaries';
    }

    /**
     * @inheritdoc
     */
    public function getColNames()
    {
        return [
            'summary_id',
            'thread_id',
            'reply_count',
            'view_count',
        ];
    }

    /**
     * @inheritdoc
     */
    public function getCols()
    {
        return [
            'summary_id' => (object) [
                'name' => 'summary_id',
                'type' => 'integer',
                'size' => null,
                'scale' => null,
                'notnull' => false,
                'default' => null,
                'autoinc' => false,
                'primary' => true,
            ],
            'thread_id' => (object) [
                'name' => 'thread_id',
                'type' => 'integer',
                'size' => null,
                'scale' => null,
                'notnull' => true,
                'default' => null,
                'autoinc' => false,
                'primary' => false,
            ],
            'reply_count' => (object) [
                'name' => 'reply_count',
                'type' => 'integer',
                'size' => null,
                'scale' => null,
                'notnull' => true,
                'default' => null,
                'autoinc' => false,
                'primary' => false,
            ],
            'view_count' => (object) [
                'name' => 'view_count',
                'type' => 'integer',
                'size' => null,
                'scale' => null,
                'notnull' => true,
                'default' => null,
                'autoinc' => false,
                'primary' => false,
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function getPrimaryKey()
    {
        return [
            'summary_id',
        ];
    }

    /**
     * @inheritdoc
     */
    public function getAutoinc()
    {
        return 'summary_id';
    }

    /**
     * @inheritdoc
     */
    public function getColDefaults()
    {
        return [
            'summary_id' => null,
            'thread_id' => null,
            'reply_count' => null,
            'view_count' => null,
        ];
    }
}
